version: "3"
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: node:local
  composer:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    image: composer:local
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
  nginx:
    build:
      context: ./docker/nginx
    links:
      - "php:php.local"
    ports:
      - "8888:80"
