version: "3.7"
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: local-node:prod
  composer:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    image: local-composer:prod
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: local-php:prod
    depends_on:
      - node
      - composer
    entrypoint: ""
    command: "killall -KILL php-fpm"
  php-dev:
    build:
      context: .
      dockerfile: ./docker/php/dev.Dockerfile
    image: local-php:dev
    depends_on:
      - php
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=4B7949ED977293B4CE603D689E6B3B98
      - APP_DEBUG=true
      - APP_URL=http://localhost:8888
    volumes:
      - "./laravel:/var/www"
      - "/var/www/vendor"
      - "/var/www/bootstrap"
      - "/var/www/storage"
  nginx:
    build:
      context: ./docker/nginx
    image: local-nginx:prod
    links:
      - "php-dev:php.local"
    ports:
      - "8888:80"
